server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/municipality/config-repo
          default-label: main
          search-paths: config
  security:
    user:
      name: configuser
      password: configpass

management:
  endpoints:
    web:
      exposure:
        include: health,info